const Database = require('better-sqlite3');

function createNetgsmStore({ databasePath, fetchImpl = global.fetch }) {
  const db = new Database(databasePath); db.pragma('journal_mode = WAL');
  db.exec(`CREATE TABLE IF NOT EXISTS netgsm_settings (
    id INTEGER PRIMARY KEY CHECK(id=1), username TEXT NOT NULL DEFAULT '', password TEXT NOT NULL DEFAULT '',
    msgheader TEXT NOT NULL DEFAULT '', encoding TEXT NOT NULL DEFAULT 'TR', iysfilter TEXT NOT NULL DEFAULT '0',
    appname TEXT NOT NULL DEFAULT 'NetRelay', enabled INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL DEFAULT 0
  ); INSERT OR IGNORE INTO netgsm_settings(id) VALUES(1);`);
  const row = () => db.prepare('SELECT * FROM netgsm_settings WHERE id=1').get();
  function settings(includePassword = false) { const x=row(); return { username:x.username,password:includePassword?x.password:'',hasPassword:Boolean(x.password),msgheader:x.msgheader,encoding:x.encoding,iysfilter:x.iysfilter,appname:x.appname,enabled:x.enabled===1,updatedAt:x.updated_at }; }
  function save(input) { const current=settings(true), value={username:String(input.username||'').trim(),password:String(input.password||'')||current.password,msgheader:String(input.msgheader||'').trim(),encoding:['UTF-8','TR','UNICODE'].includes(input.encoding)?input.encoding:'TR',iysfilter:['0','11','12'].includes(String(input.iysfilter))?String(input.iysfilter):'0',appname:String(input.appname||'NetRelay').trim().slice(0,50),enabled:input.enabled?1:0,now:Date.now()}; if(!value.username)throw new Error('Netgsm API kullanıcı adı zorunludur.');if(!value.password)throw new Error('Netgsm API alt kullanıcı şifresi zorunludur.');if(value.msgheader.length<3||value.msgheader.length>11)throw new Error('Gönderici başlığı 3-11 karakter olmalıdır.');db.prepare(`UPDATE netgsm_settings SET username=@username,password=@password,msgheader=@msgheader,encoding=@encoding,iysfilter=@iysfilter,appname=@appname,enabled=@enabled,updated_at=@now WHERE id=1`).run(value); }
  const phone = (value) => { let x=String(value||'').replace(/[\s()-]/g,'');if(x.startsWith('+90'))x=x.slice(3);else if(x.startsWith('0')&&!x.startsWith('00'))x=x.slice(1);if(!/^\d{10,15}$/.test(x))throw new Error(`Geçersiz SMS numarası: ${value}`);return x; };
  async function send(numbers, message, ignoreEnabled = false) { const config=settings(true);if(!ignoreEnabled&&!config.enabled)return {skipped:true};if(!config.username||!config.password||!config.msgheader)throw new Error('Netgsm ayarları eksik.');const recipients=[...new Set(String(numbers||'').split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean).map(phone))];if(!recipients.length)throw new Error('En az bir SMS alıcısı gerekli.');const msg=String(message||'').trim();if(!msg||msg.length>912)throw new Error('SMS metni 1-912 karakter olmalıdır.');const response=await fetchImpl('https://api.netgsm.com.tr/sms/rest/v2/send',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${config.username}:${config.password}`).toString('base64')}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({msgheader:config.msgheader,messages:recipients.map(no=>({msg,no})),encoding:config.encoding,iysfilter:config.iysfilter,appname:config.appname})});let result;try{result=await response.json()}catch{throw new Error(`Netgsm geçersiz yanıt verdi (HTTP ${response.status}).`)}if(!response.ok||result.code!=='00')throw new Error(`Netgsm SMS hatası ${result.code||response.status}: ${result.description||'Bilinmeyen hata'}`);return result; }
  return { getState:()=>settings(false),save,send,sendTest:(number)=>send(number,`NetRelay test SMS - ${new Date().toLocaleString('tr-TR')}`,true),close:()=>db.close() };
}
module.exports={createNetgsmStore};
